### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/manufacture-reporting#31]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] report_mrp_bom_matrix - By @mpanarin - #34 
- [x] mrp_bom_current_stock - By @jbeficent - #30 
- [x] mrp_bom_structure_xlsx - By @hveficent  - #33 
- [x] mrp_bom_structure_xlsx_level_1 - By @lreficent - #40 
- [x] ~~mrp_webkit~~

**Comment by HviorForgeFlow** [comment]
Migrating mrp_bom_structure_xlsx to 11.0

**Comment by emagdalenaC2i** [comment]
@pedrobaeza 
mrp_bom_structure_xlsx #33 is done
mrp_bom_structure_xlsx_level_1 #40 is done

**Comment by emagdalenaC2i** [comment]
@pedrobaeza you can check mrp_bom_current_stock (#30) because it is merged

**Comment by pedrobaeza** [comment]
Closing as completed
